// The languages the Code form offers (design.md §13.48: a searchable list). Any
// other name can still be typed; the highlighter shows an unknown one as plain text.
export const CODE_LANGUAGES = [
  "bash",
  "c",
  "cpp",
  "csharp",
  "css",
  "dart",
  "diff",
  "dockerfile",
  "elixir",
  "go",
  "graphql",
  "html",
  "ini",
  "java",
  "javascript",
  "js",
  "json",
  "jsx",
  "kotlin",
  "lua",
  "markdown",
  "php",
  "powershell",
  "prisma",
  "python",
  "ruby",
  "rust",
  "scss",
  "shell",
  "sql",
  "svelte",
  "swift",
  "toml",
  "ts",
  "tsx",
  "typescript",
  "vue",
  "xml",
  "yaml",
  "text",
] as const;
